platform :ios, '8.0'
use_frameworks!
pod 'MJRefresh'
pod 'SDWebImage', '~> 3.7.3'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'SBJson', '~> 4.0.2'
pod 'SwiftyJSON'
pod 'Alamofire', '~> 3.0'
pod 'DGElasticPullToRefresh'
pod 'PagingMenuController'
pod 'SKPhotoBrowser'
pod 'ImagePickerSheetController', '~> 0.9.1'
pod 'Material', '~> 1.0'