platform :ios, '8.0'
use_frameworks!
pod 'MJRefresh'
pod 'SDWebImage', '~> 3.7.3'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'SBJson', '~> 4.0.2'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'Alamofire', '~> 3.0'
pod 'DGElasticPullToRefresh', '1.0.2'
pod 'PagingMenuController'
